# Generated by Django 3.2.4 on 2021-06-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userkey', models.IntegerField()),
                ('videoNo', models.IntegerField()),
                ('emotion_surprise', models.FloatField()),
                ('emotion_fear', models.FloatField()),
                ('emotion_disgust', models.FloatField()),
                ('emotion_happy', models.FloatField()),
                ('emotion_sadness', models.FloatField()),
                ('emotion_angry', models.FloatField()),
                ('emotion_neutral', models.FloatField()),
                ('gaze_mean', models.TextField()),
                ('face_angle_mean', models.TextField()),
                ('shoulder_angle_mean', models.TextField()),
                ('shoulder_move_left', models.TextField()),
                ('shoulder_move_right', models.TextField()),
                ('shoulder_move_center', models.TextField()),
                ('hand_count', models.IntegerField()),
                ('hand_time', models.FloatField()),
            ],
            options={
                'db_table': 'IM_video_Result',
            },
        ),
    ]
