# Generated by Django 3.2.4 on 2021-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im_video', '0002_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_data',
            name='videobyte',
            field=models.TextField(),
        ),
    ]
