# Generated by Django 3.2.4 on 2021-07-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im_video', '0003_alter_input_data_videobyte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='input_data',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='emotion_neutral',
            new_name='emotion_aversion',
        ),
    ]
